console.group('Unit 6')
console.log('IsNumber: ' + Validate.isNumber(36))
console.log('IsInt: ' + Validate.isInt(6.1))
console.log('IsFloat: ' + Validate.isFloat(-4.2))
console.log('IsChar: ' + Validate.isChar('g'))
console.log('IsString: ' + Validate.isString('string'))
console.log('IsBoolean: ' + Validate.isBoolean(true))
console.log('IsArray: ' + Validate.isArray([1, 2, 3, 4]))
console.log('toMoney: ' + Validate.toMoney(2356.5))
console.groupEnd()